//
//  CategoryListWorker.swift
//  CleanTodoey
//
//  Created by João Pedro Giarrante on 25/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit
import RealmSwift

protocol CategoryListDatabaseLogic {
    
    // MARK: Fetch Categories
    func fetchCategories() -> Promise<CategoryList.FetchCategories.Response>
    
    // MARK: Update Categories
    func updateCategories(with request: CategoryList.UpdateCategories.Request) -> Promise<CategoryList.UpdateCategories.Response>
}

class CategoryListWorker: CategoryListDatabaseLogic {
    
    // MARK: Properties
    let realm = try! Realm()
    
    
    // MARK: Fetch Categories
    func fetchCategories() -> Promise<CategoryList.FetchCategories.Response> {
        return Promise { seal in
            let response = CategoryList.FetchCategories.Response(categories: realm.objects(Category.self))
            seal.fulfill(response)
        }
    }
    
    
    // MARK: Update Categories
    func updateCategories(with request: CategoryList.UpdateCategories.Request) -> Promise<CategoryList.UpdateCategories.Response> {
        return Promise { seal in
            do {
                if(request.method == CategoryList.UpdateCategories.Request.Method.add) {
                    try realm.write {
                        realm.add(request.category)
                        seal.fulfill(CategoryList.UpdateCategories.Response(addedCategory: request.category))
                    }
                } else if(request.method == CategoryList.UpdateCategories.Request.Method.remove) {
                    try realm.write {
                        realm.delete(request.category)
                        seal.fulfill(CategoryList.UpdateCategories.Response(removedCategory: request.category))
                    }
                }
                
            } catch {
                seal.fulfill(CategoryList.UpdateCategories.Response(error: error))
            }
        }
    }
}
