//
//  CategoryListInteractor.swift
//  CleanTodoey
//
//  Created by João Pedro Giarrante on 25/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryListBusinessLogic
{
  func fetchCategories(request: CategoryList.FetchCategories.Request)
}

protocol CategoryListDataStore
{
  //var name: String { get set }
}

class CategoryListInteractor: CategoryListBusinessLogic, CategoryListDataStore
{
  var presenter: CategoryListPresentationLogic?
  var worker: CategoryListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func fetchCategories(request: CategoryList.FetchCategories.Request)
  {
    worker = CategoryListWorker()
    worker?.fetchCategories()
    
    let response = CategoryList.FetchCategories.Response()
    presenter?.presentCategories(response: response)
  }
}
