//
//  CategoryListViewController.swift
//  CleanTodoey
//
//  Created by João Pedro Giarrante on 25/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryListDisplayLogic: class
{
  func displayCategories(viewModel: CategoryList.FetchCategories.ViewModel)
}

class CategoryListViewController: UIViewController, CategoryListDisplayLogic
{
  var interactor: CategoryListBusinessLogic?
  var router: (NSObjectProtocol & CategoryListRoutingLogic & CategoryListDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CategoryListInteractor()
    let presenter = CategoryListPresenter()
    let router = CategoryListRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    getCategories()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func getCategories()
  {
    let request = CategoryList.FetchCategories.Request()
    interactor?.fetchCategories(request: request)
  }
  
  func displayCategories(viewModel: CategoryList.FetchCategories.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
