//
//  CategoryListModels.swift
//  CleanTodoey
//
//  Created by João Pedro Giarrante on 25/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum CategoryListModel {
    // MARK: Fetch Categories
    
    enum FetchCategories {
        struct Response {
            var categories: Results<Category>?
        }
        struct ViewModel {
            var categories: Array<Category>?
            var errorString: String?
        }
    }
    
    
    // MARK: Update Categories
    
    enum UpdateCategories {
        struct Request {
            enum Method {
                case add
                case remove
            }
            var method: Method
            var category: Category
        }
        struct Response {
            var addedCategory: Category?
            var removedCategory: Category?
            var categories: Array<Category>? = []
            var error: Error?
        }
        struct ViewModel {
            var categories: Array<Category>? = []
            var errorString: String?
        }
    }
    
    // MARK: Filter Categories
    
    enum FilterCategories {
        struct Request {
            var text: String?
        }
        struct Response {
            var categories: Results<Category>?
            var error: Error?
        }
        struct ViewModel {
            var categories: Array<Category>? = []
            var errorString: String?
        }
    }
}
