//
//  TodoListModels.swift
//  CleanTodoey
//
//  Created by João Pedro Giarrante on 25/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum TodoListModel {
    // MARK: Fetch Items
    
    enum FetchItems {
        struct Request {
            var currentCategory: Category?
        }
        struct Response {
            var items: Results<Item>?
            var currentCategory: Category?
        }
        struct ViewModel {
            var items: Array<Item>?
            var errorString: String?
            var currentCategory: Category?
        }
    }
    
    
    // MARK: Update Items
    
    enum UpdateItems {
        struct Request {
            enum Method {
                case add
                case remove
            }
            var method: Method
            var item: Item
            var currentCategory: Category?
        }
        struct Response {
            var updatedCategory: Category = Category()
            var error: Error?
        }
        struct ViewModel {
            var errorString: String?
            var updatedCategory: Category = Category()
        }
    }
    
    
    // MARK: Reorder Items
    
    enum ReorderItems {
        struct Request {
            var currentCategory: Category = Category()
            var from: Int?
            var to: Int?
        }
    }
    
    
    // MARK: Update Items
    
    enum GetSelectedCategory {
        struct Response {
            var selectedCategory: Category
        }
        struct ViewModel {
            var selectedCategory: Category
        }
    }
}
